#[[main]]
#  name = "Posts"
#  url = "/posts/"
#  weight = 10

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 20

[[main]]
  name = "Book a Call"
  url = "https://calendly.com/andrii-sudak/30min"
  weight = 30
