#[[main]]
#  name = "Main"
#  url = "/"
#  weight = 5
#
#[[main]]
#  name = "Posts"
#  url = "/posts/"
#  weight = 10

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 20

[[main]]
  name = "Booking"
  url = "https://andrii-sudak.com/book"
  weight = 30
