homepage.layout = "profile"

[author]
name = "Andrii Sudak"
image = "img/author.jpg"
headline = "Father of two | Open-minded person | DevOps Engineer | Poland, Krakow"
links = [
    { simplex = "https://smp18.simplex.im/a#ftV-6nbHlK8TwrWlSYVq7FsjuTS-8O7IpNgrXfjuPuw" },
    { signal = "https://signal.me/#eu/BGNUrD5nDWs2ArKIOWz1mMZsXSaivLDBEkoQ1C6JO4IYx89eTuJLiJsbzTt7Oba1" },
    { threema = "https://threema.id/NXS5Y2VP" },
    { email = "mailto:contact@andrii-sudak.com" },
    { whatsapp = "https://wa.me/qr/HGVTMDBQGGE3A1" },
    { messanger = "https://m.me/andriisudak" }
]

[article]
  showAuthorBottom = true
  showWordCount = false
