homepage.layout = "profile"

[author]
name = "Andrii Sudak"
image = "img/author.jpg"
headline = "Father of two | Open-minded person | DevOps Engineer | Ukraine, Lviv"
links = [
    { simplex = "https://simplex.chat/contact#/?v=2-7&smp=smp%3A%2F%2FPtsqghzQKU83kYTlQ1VKg996dW4Cw4x_bvpKmiv8uns%3D%40smp18.simplex.im%2FQwHLSYav2vXh8xfmRt-XywrQtUJk5MIe%23%2F%3Fv%3D1-3%26dh%3DMCowBQYDK2VuAyEAiyM-1NDF29x8hrmNc3Uj5ZdokaXO91J-uD_I9ZkfHT8%253D%26srv%3Dlyqpnwbs2zqfr45jqkncwpywpbtq7jrhxnib5qddtr6npjyezuwd3nqd.onion" },
    { signal = "https://signal.me/#eu/BGNUrD5nDWs2ArKIOWz1mMZsXSaivLDBEkoQ1C6JO4IYx89eTuJLiJsbzTt7Oba1" },
    { threema = "https://threema.id/NXS5Y2VP" },
    { gnupg = "https://keys.openpgp.org/vks/v1/by-fingerprint/A88C4CE4DA150F2F4E9A53D5378609B5643F5A4D" },
    { email = "mailto:contact@andrii-sudak.com" },
    { whatsapp = "https://wa.me/qr/HGVTMDBQGGE3A1" },
    { github = "https://github.com/andrii-sudak" },
    { gitlab = "https://gitlab.com/andrii-sudak" },
    { instagram = "https://www.instagram.com/andrii_sudak" },
    { facebook = "https://www.facebook.com/andriisudak" },
    { linkedin = "https://www.linkedin.com/in/andrii-sudak" },
    { mastodon = "https://infosec.exchange/@andrii_sudak" },
    { youtube = "https://www.youtube.com/channel/UCKJLt9NowBWdYODu7Zc3UYA" },
    { discord = "https://discordapp.com/users/1308894452621901895" },
    { soundcloud = "https://soundcloud.com/andrii-sudak" }
]

colorScheme = "avocado"  # TODO: Change to the custom Solarized https://github.com/andrii-sudak/website/issues/2
autoSwitchAppearance=true

enableSearch=false

footer.showAppearanceSwitcher=false
