#enableA11y = true
autoSwitchAppearance = true
enableSearch = false
logo = "img/logo.svg"
#replyByEmail = true
#highlightCurrentMenuArea = true
defaultFeaturedImage = "img/feature_default.png"
disableImageZoom = true
enableFontPreload = true


[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5

[author]
  name = "Andrii Sudak"
  image = "img/author.jpg"
  headline = "Father of two | Open-minded person | DevOps Engineer | Poland, Krakow"
#  email = "contact@andrii-sudak.com"
  links = [
    { threema = "https://threema.id/DNZHSZRH" },
    { signal = "https://signal.me/#eu/BGNUrD5nDWs2ArKIOWz1mMZsXSaivLDBEkoQ1C6JO4IYx89eTuJLiJsbzTt7Oba1" },
    { email = "mailto:contact@andrii-sudak.com" },
    { whatsapp = "https://wa.me/qr/HGVTMDBQGGE3A1"},
    { messanger = "https://m.me/andriisudak"}
  ]

[article]
  showWordCount = false
  showReadingTime = false
  showDateUpdated = true
  showAuthorBottom = true
#  showBreadcrumbs = true

[footer]
  showThemeAttribution = false
