baseURL = 'https://andrii-sudak.com'
languageCode = 'en-us'
title = "Andrii Sudak's Website"

[params.author]
name = "Andrii Sudak"
image = "img/author.jpg"
headline = "Father of two | Open-minded person | DevOps Engineer | Ukraine, Lviv"
links = [
  { signal = "https://signal.me/#eu/BGNUrD5nDWs2ArKIOWz1mMZsXSaivLDBEkoQ1C6JO4IYx89eTuJLiJsbzTt7Oba1" },
  { threema = "https://threema.id/NXS5Y2VP" },
  { gnupg = "https://keys.openpgp.org/vks/v1/by-fingerprint/A88C4CE4DA150F2F4E9A53D5378609B5643F5A4D" },
  { email = "mailto:contact@andrii-sudak.com" },
  { whatsapp = "https://wa.me/qr/HGVTMDBQGGE3A1" },
  { github = "https://github.com/andrii-sudak" },
  { gitlab = "https://gitlab.com/andrii-sudak" },
  { instagram = "https://www.instagram.com/andrii_sudak" },
  { facebook = "https://www.facebook.com/andriisudak" },
  { linkedin = "https://www.linkedin.com/in/andrii-sudak" },
  { mastodon = "https://infosec.exchange/@andrii_sudak" },
  { youtube = "https://www.youtube.com/channel/UCKJLt9NowBWdYODu7Zc3UYA" },
  { discord = "https://discordapp.com/users/1308894452621901895" },
  { soundcloud = "https://soundcloud.com/andrii-sudak" }
]
